Resources:
    # DynamoDB resources
  ClientGroupMonitorTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: clientId
          AttributeType: S
        - AttributeName: clientGroupMonitorId
          AttributeType: S
      KeySchema:
        - AttributeName: clientId
          KeyType: HASH
        - AttributeName: clientGroupMonitorId
          KeyType: RANGE        
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.prefix}-ClientGroupMonitorTable