VARIABLE_DICTIONARY = {
    "EA_A_I": {"Unidad": "kWh", "Nombre": "Energía activa importada - LA"},
    "EA_B_I": {"Unidad": "kWh", "Nombre": "Energía activa importada - LB"},
    "EA_C_I": {"Unidad": "kWh", "Nombre": "Energía activa importada - LC"},
    "EA_T_I": {"Unidad": "kWh", "Nombre": "Energía activa importada - Total"},
    "EA_A_E": {"Unidad": "kWh", "Nombre": "Energía activa exportada - LA"},
    "EA_B_E": {"Unidad": "kWh", "Nombre": "Energía activa exportada - LB"},
    "EA_C_E": {"Unidad": "kWh", "Nombre": "Energía activa exportada - LC"},
    "EA_T_E": {"Unidad": "kWh", "Nombre": "Energía activa exportada - Total"},
    "ER_A_I": {"Unidad": "kvarh", "Nombre": "Energía reactiva importada - LA"},
    "ER_B_I": {"Unidad": "kvarh", "Nombre": "Energía reactiva importada - LB"},
    "ER_C_I": {"Unidad": "kvarh", "Nombre": "Energía reactiva importada - LC"},
    "ER_T_I": {"Unidad": "kvarh", "Nombre": "Energía reactiva importada - Total"},
    "ER_A_E": {"Unidad": "kvarh", "Nombre": "Energía reactiva exportada - LA"},
    "ER_B_E": {"Unidad": "kvarh", "Nombre": "Energía reactiva exportada - LB"},
    "ER_C_E": {"Unidad": "kvarh", "Nombre": "Energía reactiva exportada - LC"},
    "ER_T_E": {"Unidad": "kvarh", "Nombre": "Energía reactiva exportada - Total"},
    "FP_A": {"Unidad": "-", "Nombre": "Factor de potencia - LA"},
    "FP_B": {"Unidad": "-", "Nombre": "Factor de potencia - LB"},
    "FP_C": {"Unidad": "-", "Nombre": "Factor de potencia - LC"},
    "FP_T": {"Unidad": "-", "Nombre": "Factor de potencia - Total"},
    "F": {"Unidad": "Hz", "Nombre": "Frecuencia"},
    "ITHD_A": {"Unidad": "-", "Nombre": "Distorsión armónica de corriente - LA"},
    "ITHD_B": {"Unidad": "-", "Nombre": "Distorsión armónica de corriente - LB"},
    "ITHD_C": {"Unidad": "-", "Nombre": "Distorsión armónica de corriente - LC"},
    "ITHD_P": {"Unidad": "-", "Nombre": "Distorsión armónica de corriente - Promedio"},
    "I_A": {"Unidad": "A", "Nombre": "Corriente - LA"},
    "I_B": {"Unidad": "A", "Nombre": "Corriente - LB"},
    "I_C": {"Unidad": "A", "Nombre": "Corriente - LC"},
    "PAP_A": {"Unidad": "kVA", "Nombre": "Potencia aparente - LA"},
    "PAP_B": {"Unidad": "kVA", "Nombre": "Potencia aparente - LB"},
    "PAP_C": {"Unidad": "kVA", "Nombre": "Potencia aparente - LC"},
    "PAP_T": {"Unidad": "kVA", "Nombre": "Potencia aparente - Total"},
    "PA_A": {"Unidad": "kW", "Nombre": "Potencia activa - LA"},
    "PA_B": {"Unidad": "kW", "Nombre": "Potencia activa - LB"},
    "PA_C": {"Unidad": "kW", "Nombre": "Potencia activa - LC"},
    "PA_T": {"Unidad": "kW", "Nombre": "Potencia activa - Total"},
    "PR_A": {"Unidad": "kvar", "Nombre": "Potencia reactiva - LA"},
    "PR_B": {"Unidad": "kvar", "Nombre": "Potencia reactiva - LB"},
    "PR_C": {"Unidad": "kvar", "Nombre": "Potencia reactiva - LC"},
    "PR_T": {"Unidad": "kvar", "Nombre": "Potencia reactiva - Total"},
    "VA_IA": {"Unidad": "°", "Nombre": "Ángulo entre VA e IA"},
    "VB_IB": {"Unidad": "°", "Nombre": "Ángulo entre VB e IB"},
    "VC_IC": {"Unidad": "°", "Nombre": "Ángulo entre VC e IC"},
    "VTHD_A": {"Unidad": "-", "Nombre": "Distorsión armónica de voltaje - LA"},
    "VTHD_B": {"Unidad": "-", "Nombre": "Distorsión armónica de voltaje - LB"},
    "VTHD_C": {"Unidad": "-", "Nombre": "Distorsión armónica de voltaje - LC"},
    "VTHD_P": {"Unidad": "-", "Nombre": "Distorsión armónica de voltaje - Promedio"},
    "V_A": {"Unidad": "V", "Nombre": "Voltaje - LA"},
    "V_B": {"Unidad": "V", "Nombre": "Voltaje - LB"},
    "V_C": {"Unidad": "V", "Nombre": "Voltaje - LC"},
}
